from dotenv import load_dotenv
from typing import List
from pydantic import BaseModel, Field
from langchain.agents import create_agent
from langchain.tools import tool
from langchain.messages import HumanMessage
from langchain_openai import ChatOpenAI
from tavily import TavilyClient

load_dotenv()

tavily = TavilyClient()


class Source(BaseModel):
    """
    Schema for a source used by the agent
    """

    url: str = Field(description="The URL of the source")


class AgentResponse(BaseModel):
    """
    Schema for the response generated by the agent with answer and sources
    """

    answer: str = Field(description="The answer of the agent")
    sources: List[Source] = Field(
        default_factory=list, description="List of sources used to generate the answer"
    )


@tool
def search(query: str):
    """
    Tool that searches over the internet
    Args:
        query - The query to search for
    Returns:
        The search result
    """
    print(f"Searching for {query}")
    return tavily.search(query=query)


llm = ChatOpenAI()
tools = [search]
agent = create_agent(model=llm, tools=tools, response_format=AgentResponse)


def main():
    response = agent.invoke(
        {
            "messages": [
                HumanMessage(
                    content="What are the top 3 job positings for AI engineer on linkedin?"
                )
            ]
        }
    )
    print(response)


if __name__ == "__main__":
    main()
